// Approximate US grocery prices in dollars per 100g, based on national
// averages. Big retailers don't publish public price APIs, so these are
// estimates — the per-store multipliers below adjust for each chain's
// typical price level.

// Keys must match the nutrition table keys in lib/nutrition.ts
export const PRICE_PER_100G: Record<string, number> = {
  "chicken breast": 0.99,
  "chicken thigh": 0.66,
  chicken: 0.8,
  "lean ground turkey": 1.2,
  turkey: 1.1,
  "ground beef": 1.2,
  "beef mince": 1.2,
  "minced beef": 1.2,
  steak: 2.4,
  beef: 1.5,
  "pork tenderloin": 1.0,
  "pork belly": 1.3,
  pork: 0.9,
  "turkey bacon": 1.3,
  bacon: 1.5,
  lamb: 2.2,
  salmon: 2.6,
  tuna: 1.5,
  cod: 2.2,
  "white fish": 1.8,
  shrimp: 2.2,
  prawns: 2.2,
  tofu: 0.55,
  egg: 0.55,
  butter: 1.1,
  "light butter": 1.2,
  "olive oil": 1.1,
  "vegetable oil": 0.5,
  "sesame oil": 1.8,
  "coconut oil": 1.5,
  oil: 0.7,
  "heavy cream": 0.85,
  "double cream": 0.85,
  "evaporated milk": 0.55,
  "half and half": 0.5,
  cream: 0.8,
  "skim milk": 0.11,
  milk: 0.11,
  "greek yogurt": 0.5,
  yogurt: 0.4,
  "sour cream": 0.45,
  "light cream cheese": 0.95,
  "cream cheese": 0.9,
  parmesan: 2.2,
  "reduced-fat cheese": 1.2,
  "reduced-fat cheddar": 1.2,
  cheddar: 1.1,
  mozzarella: 1.0,
  feta: 1.4,
  cheese: 1.1,
  "chickpea pasta": 0.9,
  "whole-wheat pasta": 0.45,
  fettuccine: 0.35,
  spaghetti: 0.35,
  linguine: 0.35,
  penne: 0.35,
  macaroni: 0.35,
  lasagne: 0.4,
  pasta: 0.35,
  "cauliflower rice": 0.7,
  "zucchini noodles": 0.9,
  "courgette noodles": 0.9,
  "rice noodles": 0.6,
  noodles: 0.5,
  "brown rice": 0.3,
  rice: 0.25,
  quinoa: 0.7,
  flour: 0.12,
  breadcrumbs: 0.5,
  "bread crumbs": 0.5,
  bread: 0.4,
  "low-carb tortilla": 1.0,
  tortilla: 0.6,
  potato: 0.18,
  "sweet potato": 0.3,
  "monk fruit sweetener": 1.8,
  sugar: 0.3,
  honey: 1.0,
  "maple syrup": 1.6,
  onion: 0.25,
  garlic: 0.9,
  ginger: 0.9,
  "tomato puree": 0.4,
  "tomato sauce": 0.4,
  "tomato paste": 0.5,
  "chopped tomatoes": 0.35,
  tomato: 0.45,
  "light coconut milk": 0.6,
  "coconut milk": 0.6,
  "light mayonnaise": 0.75,
  mayonnaise: 0.7,
  avocado: 0.8,
  "black beans": 0.35,
  "kidney beans": 0.35,
  chickpeas: 0.35,
  lentils: 0.4,
  beans: 0.35,
  broccoli: 0.5,
  spinach: 0.9,
  kale: 0.7,
  mushroom: 0.9,
  "bell pepper": 0.7,
  zucchini: 0.55,
  courgette: 0.55,
  cucumber: 0.4,
  carrot: 0.3,
  celery: 0.4,
  peas: 0.4,
  corn: 0.35,
  cabbage: 0.25,
  lettuce: 0.5,
  "soy sauce": 0.5,
  "fish sauce": 0.7,
  "oyster sauce": 0.8,
  "peanut butter": 0.6,
  peanuts: 0.6,
  cashews: 1.6,
  almonds: 1.4,
  "chicken stock": 0.15,
  "beef stock": 0.15,
  stock: 0.15,
  broth: 0.15,
  wine: 1.0,
  "lemon juice": 0.6,
  lemon: 0.7,
  lime: 0.7,
  cornstarch: 0.4,
  cornflour: 0.4,
};

export interface Chain {
  pattern: RegExp;
  label: string;
  /** Typical price level vs national average (1.0 = average) */
  multiplier: number;
}

// Big retail chains only — matched against OpenStreetMap store names.
export const BIG_CHAINS: Chain[] = [
  { pattern: /walmart/i, label: "Walmart", multiplier: 0.9 },
  { pattern: /\btarget\b/i, label: "Target", multiplier: 1.05 },
  { pattern: /h-?e-?b\b|heb plus/i, label: "H-E-B", multiplier: 0.95 },
  { pattern: /sprouts/i, label: "Sprouts Farmers Market", multiplier: 1.15 },
  { pattern: /kroger/i, label: "Kroger", multiplier: 1.0 },
  { pattern: /costco/i, label: "Costco", multiplier: 0.85 },
  { pattern: /sam'?s club/i, label: "Sam's Club", multiplier: 0.85 },
  { pattern: /\baldi\b/i, label: "Aldi", multiplier: 0.85 },
  { pattern: /whole foods/i, label: "Whole Foods Market", multiplier: 1.35 },
  { pattern: /trader joe/i, label: "Trader Joe's", multiplier: 1.0 },
  { pattern: /safeway/i, label: "Safeway", multiplier: 1.1 },
  { pattern: /albertsons/i, label: "Albertsons", multiplier: 1.1 },
  { pattern: /publix/i, label: "Publix", multiplier: 1.1 },
  { pattern: /meijer/i, label: "Meijer", multiplier: 0.95 },
  { pattern: /wegmans/i, label: "Wegmans", multiplier: 1.0 },
  { pattern: /winco/i, label: "WinCo Foods", multiplier: 0.85 },
  { pattern: /food lion/i, label: "Food Lion", multiplier: 0.95 },
  { pattern: /fred meyer/i, label: "Fred Meyer", multiplier: 1.0 },
  { pattern: /king soopers/i, label: "King Soopers", multiplier: 1.0 },
  { pattern: /ralphs/i, label: "Ralphs", multiplier: 1.0 },
  { pattern: /randalls/i, label: "Randalls", multiplier: 1.1 },
  { pattern: /tom thumb/i, label: "Tom Thumb", multiplier: 1.1 },
  { pattern: /stop & shop/i, label: "Stop & Shop", multiplier: 1.05 },
  { pattern: /giant\b/i, label: "Giant", multiplier: 1.05 },
];

export function matchChain(storeName: string): Chain | null {
  for (const chain of BIG_CHAINS) {
    if (chain.pattern.test(storeName)) return chain;
  }
  return null;
}
